inspirehep/inspirehep-ui

README.md
src/actions/__tests__/search.test.js
src/actions/search.js
src/common/__tests__/utils.test.js
src/common/containers/AggregationFiltersContainer.jsx
src/common/containers/__tests__/AggregationFiltersContainer.test.jsx
src/common/containers/__tests__/__snapshots__/AggregationFiltersContainer.test.jsx.snap
src/common/utils.js

* AggregationFiltersContainer passes correct prop (`selections`) to
AggregationFilter.
* page paramter refreshed the ones if there is search with new params
except page, and location already has page parameter.

fix bugs with pagination and aggregations container

---

src/common/SearchLayout.jsx
src/literature/containers/SearchPage.jsx

* Allows to share search layout including common containers that will
exist in all search pages
TODO:
* tests
* more customization possiblities like theme color

add common parent search component

---

docker/Dockerfile
docker/conf/conf.d/default.conf
run-build-docker-image.sh

docker: dockerfile to build the image

---

src/actions/__tests__/search.test.js
src/actions/search.js

search: fix relative url issue

---

src/actions/__tests__/exceptions.test.js
src/reducers/__tests__/exceptions.test.js

add tests for exceptions dashboard's reducers and actions

---

src/holdingpen/components/ExceptionsDashboard.jsx
src/holdingpen/components/__tests__/__snapshots__/ExceptionsDashboard.test.jsx.snap

change ui for collection counts and add a label

---

src/holdingpen/containers/__tests__/ExceptionsPage.test.jsx
src/holdingpen/containers/__tests__/__snapshots__/ExceptionsPage.test.jsx.snap

add tests for exceptions-page container

---

src/actions/__tests__/literature.test.js
src/actions/__tests__/search.test.js
src/actions/literature.js
src/actions/search.js
src/common/containers/__tests__/AggregationFiltersContainer.test.jsx
src/common/containers/__tests__/PaginationContainer.test.jsx
src/common/containers/__tests__/SearchBoxContainer.test.jsx
src/common/containers/__tests__/SortByContainer.test.jsx
src/literature/containers/__tests__/DetailPage.test.jsx
src/literature/containers/__tests__/SearchPage.test.jsx

improve tests for action dispatching

---

public/index.html

global: change the title

---

.eslintrc
package.json
src/App.jsx
src/literature/index.jsx
yarn.lock

* Uses react-loadable to split code for some routes so that they are
not including into main bundle, therefore not needed to be loaded
initially. However they are loaded ASAP without blocking the user
interaction so that they are served immediately once user needs them.

user Loadable to split code into multiple chunks

---

src/holdingpen/containers/InspectPage/InspectPage.jsx
src/holdingpen/containers/__tests__/__snapshots__/InspectPage.test.jsx.snap

I would also like to add a question mark icon with a tooltip to the titles that displays more info (see https://inspirehep.zulipchat.com/#narrow/stream/122202-devel/subject/merger.20debug/near/129522128), but don't know how to pass the info to the component I would need to define.

diff correct data in InspectPage

---

src/App.scss
src/index.js

It is deprecated to import css in sass by lib-sass

move css import from sass to js file

---

src/common/components/ExpandableInlineList/__tests__/__snapshots__/ExpandableInlineList.test.jsx.snap
src/common/components/InlineList/InlineList.jsx
src/common/components/InlineList/InlineList.scss
src/common/components/InlineList/__tests__/__snapshots__/InlineList.test.jsx.snap
src/common/layouts/Footer/__tests__/__snapshots__/Footer.test.jsx.snap
src/holdingpen/components/__tests__/__snapshots__/ExceptionsDashboard.test.jsx.snap
src/home/__tests__/__snapshots__/index.test.jsx.snap
src/literature/components/AuthorList.jsx
src/literature/components/CollaborationList.jsx
src/literature/components/LiteratureItem.jsx
src/literature/components/__tests__/CollaborationList.test.jsx
src/literature/components/__tests__/__snapshots__/ArxivEprintList.test.jsx.snap
src/literature/components/__tests__/__snapshots__/AuthorList.test.jsx.snap
src/literature/components/__tests__/__snapshots__/CollaborationList.test.jsx.snap
src/literature/components/__tests__/__snapshots__/DOIList.test.jsx.snap
src/literature/components/__tests__/__snapshots__/ExternalSystemIdentifiersList.test.jsx.snap
src/literature/components/__tests__/__snapshots__/LiteratureItem.test.jsx.snap
src/literature/components/__tests__/__snapshots__/LiteratureKeywordList.test.jsx.snap
src/literature/components/__tests__/__snapshots__/PublicationInfoList.test.jsx.snap
src/literature/components/__tests__/__snapshots__/ReportNumberList.test.jsx.snap
src/literature/containers/DetailPage/DetailPage.jsx

CollaborationList: fix collaborations display

---

src/literature/containers/DetailPage/DetailPage.jsx
src/literature/containers/__tests__/DetailPage.test.jsx

Ftches resources for the new record  when record id in the url is
changed via react-router Link.

fetch resources new record when url is changed

---

src/literature/components/AuthorLink.jsx
src/literature/components/__tests__/AuthorLink.test.jsx
src/literature/components/__tests__/__snapshots__/AuthorLink.test.jsx.snap

AuthorLink: fallback to ``full_name``

---

.gitignore
src/literature/components/AuthorLink.jsx
src/literature/components/__tests__/AuthorLink.test.jsx
src/literature/components/__tests__/__snapshots__/AuthorLink.test.jsx.snap

Signed-off-by: Iuliana Voinea <iulianavoinea96@gmail.com>

AuthorLink: display `(ed.)` after each editor

---

src/literature/components/DOIList.jsx
src/literature/components/PublicationInfo.jsx
src/literature/components/__tests__/DOIList.test.jsx
src/literature/components/__tests__/PublicationInfo.test.jsx
src/literature/components/__tests__/__snapshots__/DOIList.test.jsx.snap
src/literature/components/__tests__/__snapshots__/PublicationInfo.test.jsx.snap

User-story: [INSPIR-1030](https://its.cern.ch/jira/browse/INSPIR-1030)
Screenshots

display material for dois and publication_info

---

src/literature/components/PublicationInfo.jsx
src/literature/components/__tests__/PublicationInfo.test.jsx
src/literature/components/__tests__/__snapshots__/PublicationInfo.test.jsx.snap

User-Story: [INSPIR-1031](https://its.cern.ch/jira/browse/INSPIR-1031)
[INSPIR-1032](https://its.cern.ch/jira/browse/INSPIR-1031)

Display page info (or `artid`) and `journal_issue` in `publication_info`

---

.travis.yml
deploy.sh

travis: addition of deployment

---

src/App.jsx
src/__tests__/App.test.jsx
src/__tests__/__snapshots__/App.test.jsx.snap

global: remove restricted route for holdingpen

---

src/literature/components/NumberOfPages.jsx
src/literature/components/__tests__/__snapshots__/NumberOfPages.test.jsx.snap

literature: display no_of_pages and thesis_info in seperate lines

---

src/common/components/AggregationBox.jsx
src/common/components/__tests__/AggregationBox.test.jsx
src/common/components/__tests__/__snapshots__/AggregationBox.test.jsx.snap
src/common/containers/AggregationFiltersContainer/AggregationFiltersContainer.jsx
src/common/containers/__tests__/AggregationFiltersContainer.test.jsx
src/common/containers/__tests__/__snapshots__/AggregationFiltersContainer.test.jsx.snap

aggregation: use of ``meta`` to get the ``title`` and ``order``

---

src/user/containers/LoginPage/LoginPage.jsx
src/user/containers/LoginPage/__tests__/__snapshots__/LoginPage.test.jsx.snap

User-Stroy: [INSPIR_1176](https://its.cern.ch/jira/browse/INSPIR-1176)
Screen-shot

change login page layout

---

src/common/components/Loading.jsx
src/common/components/__tests__/__snapshots__/Loading.test.jsx.snap
src/holdingpen/components/ExceptionsDashboard.jsx
src/holdingpen/components/ExceptionsTable.jsx
src/holdingpen/components/__tests__/ExceptionsDashboard.test.jsx
src/holdingpen/components/__tests__/ExceptionsTable.test.jsx
src/holdingpen/components/__tests__/__snapshots__/ExceptionsDashboard.test.jsx.snap
src/holdingpen/components/__tests__/__snapshots__/ExceptionsTable.test.jsx.snap
src/holdingpen/containers/__tests__/ExceptionsPage.test.jsx
src/holdingpen/containers/__tests__/__snapshots__/ExceptionsPage.test.jsx.snap

fix the loader on the exceptions dashboard

---

src/literature/components/CiteModalAction.jsx
src/literature/components/__tests__/__snapshots__/CiteModalAction.test.jsx.snap

User-Story: [INSPIR-1208](https://its.cern.ch/jira/browse/INSPIR-1208)

remove all obsolete options from cite

---

src/fixtures/store.js
src/holdingpen/__tests__/__snapshots__/index.test.jsx.snap
src/holdingpen/__tests__/index.test.jsx
src/literature/__tests__/__snapshots__/index.test.jsx.snap
src/literature/__tests__/index.test.jsx

User-Story: [INSPIR-1201](https://its.cern.ch/jira/browse/INSPIR-1201)
signed-off-by: Dinika Saxena <dinika.saxena@cern.ch>

add tests for sub-routes

---

src/literature/components/LiteratureItem.jsx
src/literature/components/__tests__/__snapshots__/LiteratureItem.test.jsx.snap

User-Story: [INSPIR-1273](https://its.cern.ch/jira/browse/INSPIR-1273)
Screenshot

swap icons for references and citations in literature search results

---

src/common/components/RouteOrRedirect.jsx
src/fixtures/store.js
src/middlewares/__tests__/keepPreviousUrl.test.js
src/middlewares/keepPreviousUrl.js
src/store.js
src/user/index.jsx

* Adds a middleware to keep track of previous url

redirect to previous page if login successful

---

src/common/containers/EditRecordActionContainer.jsx
src/common/containers/__tests__/EditRecordActionContainer.test.jsx
src/common/containers/__tests__/__snapshots__/EditRecordActionContainer.test.jsx.snap
src/literature/components/LiteratureItem.jsx
src/literature/components/__tests__/__snapshots__/LiteratureItem.test.jsx.snap
src/literature/containers/DetailPage/DetailPage.jsx

UserStory: [INSPIR 1229](https://its.cern.ch/jira/browse/INSPIR-1229)
Screenshot

add button to edit record

---

src/common/components/ContentBox/ContentBox.jsx
src/common/components/ResultItem.jsx
src/common/components/__tests__/__snapshots__/ContentBox.test.jsx.snap
src/common/components/__tests__/__snapshots__/ResultItem.test.jsx.snap
src/common/containers/__tests__/__snapshots__/CitationList.test.jsx.snap
src/literature/components/LiteratureItem.jsx
src/literature/components/__tests__/__snapshots__/LiteratureItem.test.jsx.snap
src/literature/components/__tests__/__snapshots__/ReferenceList.test.jsx.snap
src/literature/containers/DetailPage/DetailPage.jsx

User-Story: [INSPIR-1302](https://its.cern.ch/jira/browse/INSPIR-1302)
Screenshot

literature: move cite and reference count to the right

---

src/common/containers/SortByContainer.jsx
src/common/containers/__tests__/__snapshots__/SortByContainer.test.jsx.snap

Remove the best match option for sorting

Remove sorting by best match

---

src/common/containers/CitationListContainer.jsx
src/common/containers/__tests__/__snapshots__/CitationListContainer.test.jsx.snap
src/literature/components/ReferenceList.jsx
src/literature/components/__tests__/__snapshots__/ReferenceList.test.jsx.snap
src/literature/containers/DetailPage/DetailPage.jsx
src/literature/containers/DetailPage/DetailPage.scss

* Puts citations and references under Tabs

add tabs to detail page

---

src/submissions/components/AuthorForm.jsx
src/submissions/schemas/__tests__/author.test.js
src/submissions/schemas/author.js

submissions: fix dates for project_membership and positions

---

src/common/__tests__/utils.test.js
src/common/utils.js
src/submissions/schemas/__tests__/customSchemas.test.js
src/submissions/schemas/customSchemas.js

Considers non empty objects with only empty props as empty

submissions: fix emptyObjectOrShapeOf schema

---

src/submissions/components/AuthorForm.jsx
src/submissions/schemas/__tests__/author.test.js
src/submissions/schemas/__tests__/customSchemas.test.js
src/submissions/schemas/author.js
src/submissions/schemas/constants.js
src/submissions/schemas/customSchemas.js

Year fields are using TextField now, and year schema accepts year
strings.

change year schema and year fields

---

src/submissions/schemas/constants.js

submissions: fix typo in degree type habilitation

---

src/common/components/AuthorsAndCollaborations.jsx
src/common/components/CollaborationList.jsx
src/common/components/__tests__/AuthorsAndCollaborations.test.jsx
src/common/components/__tests__/__snapshots__/AuthorsAndCollaborations.test.jsx.snap
src/common/components/__tests__/__snapshots__/CollaborationList.test.jsx.snap

* Displays author list with limit 1 even if there are multiple
collaborations
* Displays 'for the collaborations.' if there are multiple
collaboratios and single author
* Separates collaborations list and collaborations_with_suffix list by ' and '
* Seperates each collaboration with suffix by ' and '

update authors and collaboration display

---

src/submissions/components/AuthorForm.jsx

User-Story: [INSPIR-1423](https://its.cern.ch/jira/browse/INSPIR-1423)
Screenshot

author form: Rearrange experiment fields in author form

---

src/submissions/schemas/__tests__/customSchemas.test.js
src/submissions/schemas/customSchemas.js

schemas: trim orcid value before validate

---

src/App.scss
src/common/components/AuthorLink.jsx
src/common/components/__tests__/__snapshots__/AuthorLink.test.jsx.snap
src/literature/components/ReferenceItem/ReferenceItem.jsx
src/literature/components/ReferenceItem/ReferenceItem.scss
src/literature/components/ReferenceItem/__tests__/__snapshots__/ReferenceItem.test.jsx.snap

User-Story: [INSPIR-1415](https://its.cern.ch/jira/browse/INSPIR-1415)
Screenshot

change color of secondary links to lighter gray

---

src/submissions/components/CollapsableForm/CollapseFormSection.jsx
src/submissions/components/CollapsableForm/__tests__/CollapseFormSection.test.jsx
src/submissions/components/CollapsableForm/__tests__/__snapshots__/CollapseFormSection.test.jsx.snap

User-Story: [INSPIR-1425](https://its.cern.ch/jira/browse/INSPIR-1425)
Screenshot

format section titles in author submission forms

---

src/submissions/components/AuthorForm.jsx

author form: Rearrange institutions fields in author form

---

src/__tests__/App.test.jsx
src/common/components/Logo.jsx
src/common/components/SearchBox.jsx
src/common/containers/LogoContainer.jsx
src/common/layouts/Header/Header.jsx
src/common/layouts/Header/__tests__/__snapshots__/Header.test.jsx.snap

header: remove searchbar for not authorized users

---

src/common/__tests__/authorization.test.js
src/common/authorization.js
src/common/components/Logo.jsx
src/common/layouts/Header/Header.jsx
src/common/layouts/Header/__tests__/__snapshots__/Header.test.jsx.snap

* Also adds missing test for authorization

refactor searchbox, logo authorization

---

src/literature/components/ArxivEprint.jsx
src/literature/components/__tests__/__snapshots__/ArxivEprint.test.jsx.snap

fix arxiv eprint links

---

src/submissions/components/AuthorForm.jsx
src/submissions/schemas/__tests__/author.test.js
src/submissions/schemas/author.js

* Makes family_name required
* Changes label for given_name

submissions: update name fields

---

src/submissions/schemas/constants.js

submissions: fix of arxiv category

---

src/common/containers/AggregationFiltersContainer/AggregationFiltersContainer.jsx
src/common/containers/__tests__/AggregationFiltersContainer.test.jsx
src/common/containers/__tests__/__snapshots__/AggregationFiltersContainer.test.jsx.snap

User-Story: [INSPIR-1434](https://its.cern.ch/jira/browse/INSPIR-1434)
Screenshots

AggregationFiltersContainer: remove facets when no results found

---

src/common/components/AggregationFilter.jsx
src/common/components/AggregationFilters.jsx
src/common/components/CheckboxAggregation.jsx
src/common/components/RangeAggregation/RangeAggregation.jsx
src/common/components/RangeAggregation/__tests__/RangeAggregation.test.jsx
src/common/components/__tests__/AggregationFilter.test.jsx
src/common/components/__tests__/AggregationFilters.test.jsx
src/common/components/__tests__/CheckboxAggregation.test.jsx
src/common/components/__tests__/__snapshots__/AggregationFilter.test.jsx.snap
src/common/components/__tests__/__snapshots__/AggregationFilters.test.jsx.snap

* Also moves logic specific to each type of aggregations into their own
components.

fix range aggregation display bug

---

src/common/components/AuthorAffiliationList.jsx
src/common/components/AuthorLink.jsx
src/common/components/__tests__/AuthorAffiliationList.test.jsx
src/common/components/__tests__/__snapshots__/AuthorAffiliationList.test.jsx.snap
src/common/components/__tests__/__snapshots__/AuthorLink.test.jsx.snap

Used InlineList to display all affiliations for an author separated by and

Display several affiliations for authors

---

src/authors/containers/DetailPage.jsx
src/common/components/AggregationFilters.jsx
src/common/components/CheckboxAggregation.jsx
src/common/components/__tests__/AggregationFilters.test.jsx
src/common/components/__tests__/CheckboxAggregation.test.jsx
src/common/components/__tests__/__snapshots__/AggregationFilter.test.jsx.snap
src/common/components/__tests__/__snapshots__/AggregationFilters.test.jsx.snap
src/common/components/__tests__/__snapshots__/CheckboxAggregation.test.jsx.snap

* Aggegation respects `mate.split` and only displays after `_` in this
case.
* Literature search of the author is using `facet_author_name` now.

update to work with new author facet

---

src/authors/__tests__/utils.test.js
src/authors/components/AuthorResultItem.jsx
src/authors/components/__tests__/AuthorResultItem.test.jsx
src/authors/components/__tests__/__snapshots__/AuthorResultItem.test.jsx.snap
src/authors/containers/DetailPage.jsx
src/authors/utils.js
src/common/components/AuthorAffiliationList.jsx
src/common/components/AuthorLink.jsx
src/common/components/__tests__/AuthorAffiliationList.test.jsx
src/common/components/__tests__/__snapshots__/AuthorAffiliationList.test.jsx.snap
src/common/components/__tests__/__snapshots__/AuthorLink.test.jsx.snap

INSPIR-1718 Displayed only current institutions for an author both in details and search page

several affiliations in author profiles

---

src/authors/components/PositionsTimeline.jsx
src/authors/components/__tests__/PositionsTimeline.test.jsx
src/authors/components/__tests__/__snapshots__/PositionsTimeline.test.jsx.snap

Does not display if there is only single position with display_date ==
'present'.

fix positions when display_date is "present"

---

src/authors/components/PositionsTimeline.jsx
src/authors/components/__tests__/PositionsTimeline.test.jsx
src/authors/components/__tests__/__snapshots__/PositionsTimeline.test.jsx.snap
src/authors/containers/DetailPage.jsx
src/common/components/SubContentBox.jsx
src/common/components/__tests__/SubContentBox.test.jsx
src/common/components/__tests__/__snapshots__/SubContentBox.test.jsx.snap

* Removes the logic from frontend

use should_display_positions from backend

---

src/common/utils.js

* Some user's browser still does not support that such as Chrome Mobile
v50

use Object.keys instead of .values

---

src/submissions/authors/containers/AuthorSubmissionPage.jsx
src/submissions/authors/containers/__tests__/AuthorSubmissionPage.test.jsx
src/submissions/authors/containers/__tests__/__snapshots__/AuthorSubmissionPage.test.jsx.snap
src/submissions/authors/schemas/author.js

Added query as initial form data in Author submission

---

src/literature/components/CiteModalAction.jsx
src/literature/components/__tests__/CiteModalAction.test.jsx

* Cite modal shows same selected format and content when it is opened
again after the first time.

literatue: fix cite modal bug

---

src/common/components/SortBy.jsx
src/common/components/__tests__/__snapshots__/SortBy.test.jsx.snap

Added sort by best match

---

src/common/components/UserFeedback/UserFeedback.jsx
src/common/components/UserFeedback/__tests__/__snapshots__/UserFeedback.test.jsx.snap
src/tracker.js

* checkIfTrackerIsDisabled respects browsers' "Do Not Track" feature.

detect if DoNotTrack is enabled
